"""empty message

Revision ID: 0053f7f31b61
Revises: 41561733f4d5
Create Date: 2021-02-25 02:49:43.788368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0053f7f31b61'
down_revision = '41561733f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
