"""empty message

Revision ID: 038a473669d1
Revises: 69b0346ac3de
Create Date: 2021-02-24 03:28:13.836836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038a473669d1'
down_revision = '69b0346ac3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    op.drop_table('user')
    op.drop_table('menu_item')
    op.drop_table('menu_cat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_cat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('restid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['restid'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categid', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('gluten_free', sa.VARCHAR(), nullable=True),
    sa.Column('vegetarian', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['categid'], ['menu_cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('mobile', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('open_time', sa.VARCHAR(), nullable=True),
    sa.Column('close_time', sa.VARCHAR(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('average_cost', sa.INTEGER(), nullable=True),
    sa.Column('userid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
