"""empty message

Revision ID: 12effe08fc45
Revises: e8d4097e740d
Create Date: 2021-02-24 21:30:18.247931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12effe08fc45'
down_revision = 'e8d4097e740d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
