"""empty message

Revision ID: 1839d9ac6f8e
Revises: 61cf8e779908
Create Date: 2021-02-25 02:01:20.372712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1839d9ac6f8e'
down_revision = '61cf8e779908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
