"""empty message

Revision ID: 3477e11ba252
Revises: 33fc8f6f38d3
Create Date: 2021-02-25 01:47:07.093245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3477e11ba252'
down_revision = '33fc8f6f38d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
