"""empty message

Revision ID: 57f3f7d0fca5
Revises: 3477e11ba252
Create Date: 2021-02-25 01:47:21.868922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f3f7d0fca5'
down_revision = '3477e11ba252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
