"""empty message

Revision ID: 69b0346ac3de
Revises: bbc9f81e9875
Create Date: 2021-02-24 02:47:34.549006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b0346ac3de'
down_revision = 'bbc9f81e9875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
