"""empty message

Revision ID: 815c0ae1581c
Revises: 
Create Date: 2021-02-24 17:10:47.211270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815c0ae1581c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
