"""empty message

Revision ID: b02122b6062c
Revises: ce516420d133
Create Date: 2021-02-25 02:11:46.093893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02122b6062c'
down_revision = 'ce516420d133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
