"""empty message

Revision ID: ce516420d133
Revises: 9c13e28bcd48
Create Date: 2021-02-25 02:11:43.006273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce516420d133'
down_revision = '9c13e28bcd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
