"""empty message

Revision ID: f8b36afef200
Revises: 57f3f7d0fca5
Create Date: 2021-02-25 01:47:40.426922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b36afef200'
down_revision = '57f3f7d0fca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
